services:
  db:
    image: postgres:17-alpine
    container_name: newsletter
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
      MAX_CONNECTIONS: 1000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
