application:
  host: 127.0.0.1
  base_url: "http://127.0.0.1"
database:
  require_ssl: false
email_client:
  base_url: "https://sandbox.api.mailtrap.io/api/send/2317403"
  sender_email: "test-local@gmail.com"
